config/routes.rb
Rails.application.routes.draw do

  resources :new_trivia

  root 'surveys#index'
  resources 'surveys'
  resources 'attempts'
  resources 'users', only: [:create]
  get 'process_openie', to: 'surveys#process_openie'

  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

end

app/views/shared/_flash.html.erb
<div class="container">
  <div class="flash">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= correct_flash_name(name) %>" role="alert">
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Copyright © 2013  <%= link_to 'Runtime Revolution', 'http://www.runtime-revolution.com', target: '_blank' %>, released under the MIT license.</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to surveys_path, class: 'navbar-brand' do %>
          <%= render 'shared/rr_logo' %>
        <% end -%>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= is_active?(surveys_path) %>">
            <%= link_to surveys_path do %>
              All surveys
              <span class='badge'> <%= surveys_count %> </span>
            <% end %>
          </li>
          <li class="dropdown <%= is_active?(new_survey_path) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">New <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li> <%= link_to 'Trivia', new_new_trivium_path %> </li>
            </ul>
          </li>
        </ul>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">
                Logged in as:
                <b> <%= current_user.name %> </b>
                <%= link_to '(change name)', '#', 'data-toggle': 'modal', 'data-target': '#submit-name-modal' %>
              </p>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/gem_header_info' %>
</header>

app/views/shared/_rr_logo.html.erb
<div class="logo">
   <%= image_tag("trivia-logo.png", :alt => "Trivia Gen") %>
</div>

app/views/shared/_submit_name_modal.html.erb
<div id="submit-name-modal" class="modal fade" data-new-user="<%= !current_user %>">
  <%= user_form do |f| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4> <%= f.label :name, 'What\'s your name?' %> </h4>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon">
                <i class="fa fa-user"></i>
              </span>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <span class="help-block">This is your username. It will be associated with each survey participation you make</span>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>