config/routes.rb
Rails.application.routes.draw do

  resources :new_trivia

  root 'surveys#index'
  resources 'surveys'
  resources 'attempts'
  resources 'users', only: [:create]
  get 'process_openie', to: 'surveys#process_openie'

  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

end

app/controllers/new_trivia_controller.rb
require 'net/http'

class NewTriviaController < ApplicationController
  before_action :set_new_trivium, only: [:show, :edit, :update, :destroy]

  # GET /new_trivia
  # GET /new_trivia.json
  def index
    @new_trivia = NewTrivium.all
  end

  # GET /new_trivia/1
  # GET /new_trivia/1.json
  def show
  end

  # GET /new_trivia/new
  def new
    @new_trivium = NewTrivium.new
  end

  # GET /new_trivia/1/edit
  def edit
  end

  # POST /new_trivia
  # POST /new_trivia.json
  def create
    @new_trivium = NewTrivium.new(new_trivium_params)
    http = Net::HTTP.new('localhost', '5000')

    request = Net::HTTP::Post.new('/openie', {'Content-Type' => 'application/json'})
    request.body = new_trivium_params.to_json

    response = http.request(request)
    @response = JSON.parse(response.body)

    http2 = Net::HTTP.new('huwalaumba.mooo.com', '5000')
    request2 = Net::HTTP::Post.new('/article', {'Content-Type' => 'application/json'})
    request2.body = new_trivium_params.to_json
    response2 = http2.request(request2)
    @response2 = JSON.parse(response2.body)

    render :index
  end

  # PATCH/PUT /new_trivia/1
  # PATCH/PUT /new_trivia/1.json
  def update
    respond_to do |format|
      if @new_trivium.update(new_trivium_params)
        format.html { redirect_to @new_trivium, notice: 'New trivium was successfully updated.' }
        format.json { render :show, status: :ok, location: @new_trivium }
      else
        format.html { render :edit }
        format.json { render json: @new_trivium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_trivia/1
  # DELETE /new_trivia/1.json
  def destroy
    @new_trivium.destroy
    respond_to do |format|
      format.html { redirect_to new_trivia_url, notice: 'New trivium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_trivium
      @new_trivium = NewTrivium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_trivium_params
      params.require(:new_trivium).permit(:content, :title)
    end
end

app/helpers/new_trivia_helper.rb
module NewTriviaHelper
end

app/views/new_trivia/_form.html.erb
<div class="container">
  <div class="flash">
    <h1>New Trivia</h1>
    <%= form_for(@new_trivium) do |f| %>
  <% if @new_trivium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_trivium.errors.count, "error") %> prohibited this new_trivium from being saved:</h2>

      <ul>
      <% @new_trivium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

  </div>
</div>

app/views/new_trivia/edit.html.erb
<h1>Editing New Trivium</h1>

<%= render 'form' %>

<%= link_to 'Show', @new_trivium %> |
<%= link_to 'Back', new_trivia_path %>

app/views/new_trivia/index.html.erb
<div class="container">
  <div class="flash">
    <p id="notice"><%= notice %></p>

    <h1>Listing New Trivia</h1>

    <h4>Title: <%= @response['title'] %></h4>
    <h4>Categories: <%= @response2['topics'] %></h4>
    <div class="row">
      <div class="col-xs-6">
        <h4>OpenIE Relation</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>First Entity</th>
              <th>Relation Type</th>
              <th>Second Type</th>
            </tr>
          </thead>

          <tbody>
            <% @response['openie_relations'].each do |r| %>
              <tr>
                <% r.each do |el| %>
                <td> <%= el %></td>
              <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xs-6">
      <h4>MITIE Relation</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>First Entity</th>
            <th>Relation Type</th>
            <th>Second Type</th>
          </tr>
        </thead>

        <tbody>
          <% @response2['mitie_relations'].each do |r| %>
            <tr>
                <% r.each do |el| %>
                <td> <%= el %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
    <br>
  </div>
</div>

app/views/new_trivia/new.html.erb
<%= render 'form' %>

app/views/new_trivia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @new_trivium.content %>
</p>

<p>
  <strong>Title:</strong>
  <%= @new_trivium.title %>
</p>

<%= link_to 'Edit', edit_new_trivium_path(@new_trivium) %> |
<%= link_to 'Back', new_trivia_path %>