config/routes.rb
Rails.application.routes.draw do

  resources :new_trivia

  root 'surveys#index'
  resources 'surveys'
  resources 'attempts'
  resources 'users', only: [:create]
  get 'process_openie', to: 'surveys#process_openie'

  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  helper 'surveys'

  before_filter :load_survey, only: [:new, :create]

  def index
    @surveys = Survey::Survey.active
  end

  def show
    @attempt = Survey::Attempt.find_by(id: params[:id])
    render :access_error if current_user.id != @attempt.participant_id
  end

  def new
    @participant = current_user

    unless @survey.nil?
      @attempt = @survey.attempts.new
      @attempt.answers.build
    end
  end

  def create
    @attempt = @survey.attempts.new(params_whitelist)
    @attempt.participant = current_user
    if @attempt.valid? && @attempt.save
      correct_options_text = @survey.correct_options.present? ? 'Bellow are the correct answers marked in green' : ''
      redirect_to attempt_path(@attempt.id), notice: "Thank you for answering #{@survey.name}! #{correct_options_text}"
    else
      build_flash(@attempt)   
      @participant = current_user
      render :new
    end
  end

  def delete_user_attempts
    Survey::Attempt.where(participant_id: params[:user_id], survey_id: params[:survey_id]).destroy_all
    redirect_to new_attempt_path(survey_id: params[:survey_id])
  end

  private

  def load_survey
    @survey = Survey::Survey.find_by(id: params[:survey_id])
  end

  def params_whitelist
    if params[:survey_attempt]
      params[:survey_attempt][:answers_attributes] = params[:survey_attempt][:answers_attributes].map { |attrs| { question_id: attrs.first, option_id: attrs.last } }
      params.require(:survey_attempt).permit(Survey::Attempt::AccessibleAttributes)
    end
  end

  def current_user
    view_context.current_user
  end
end

app/views/attempts/_form.html.erb
<h2 class="survey-title">
  <%= @survey.name %>
  <p><small><%= @attempt.survey.description %></small></p>
</h2>
<%= form_for(@attempt, url: attempt_scope(@attempt)) do |f| %>
  <%= hidden_field_tag :survey_id, @survey.id %>
  <ol class="questions">
    <%= f.fields_for :answers, get_answer_fields(@attempt) do |answer_fields| %>
      <li>
        <% question = answer_fields.object.question %>
        <p class="question"><%= question.text %></p>
        <ul class="options">
          <%= collection_radio_buttons('survey_attempt[answers_attributes]', question.id, question.options, :id, :text) do |b| %>
            <li class="radio">
              <%= b.label { b.radio_button + b.text } %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end -%>
  </ol>
  <%= f.submit "Submit", class: 'btn btn-default' %>
<% end -%>

app/views/attempts/access_error.html.erb
<div class="container">
  <p> You do not have access to this page </p>
</div>

app/views/attempts/new.html.erb
<div class="container">
  <% if @survey.nil? %>
    <p>
      This survey is no longer available
    </p>
  <% elsif @survey.avaliable_for_participant?(@participant) %>
    <%= render 'form' %>
  <% else %>
    <p>
      You have spent all the possible attempts to answer this Survey
    </p>
    <p>
      <%= link_to delete_user_attempts_path(@survey.id, session[:user_id]), method: :delete do %>
        Click here to reset the attempts
      <% end %>
    </p>
  <% end -%>
</div>

app/views/attempts/show.html.erb
<div class="container">
  <h2 class="survey-title">
    <%= @attempt.survey.name %>
    <p><small><%= @attempt.survey.description %></small></p>
  </h2>
  <ol class="questions">
    <% @attempt.answers.each do |answer| %>
      <li>
        <p class="question"> <%= answer.question.text %> </p>
        <ul class="options">
          <% answer.question.options.each do |option| %>
            <li class="radio">
              <label>
                <%= radio_button_tag '', '', the_chosen_one?(answer, option), disabled: true %>
                <% color = get_color_of_option(answer, option) %>
                <span class="<%= color %> <%= the_chosen_one?(answer, option) %>"> <%= option.text %> <%= get_weight(option) %> </span>
              </label>
              <p class="answers-number"> <%= number_of_people_who_also_answered(option.id) %> </p>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  <ol>
</div>